spring.application.name=demo-app

# application.properties
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.yqwxoyiblfnwxvgzcygr&password=JavaApp@ucss&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver

#configurar jpa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false